package com.simonjoz.katas.kyu_4;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class StripCommentsTest {

    @Test
    public void stripComments() throws Exception {
        assertEquals(
                "apples, pears\ngrapes\nbananas",
                StripComments.stripComments("apples, pears # and bananas\ngrapes\nbananas !apples", new String[]{"#", "!"})
        );

        assertEquals(
                "a\nc\nd",
                StripComments.stripComments("a #b\nc\nd $e f g", new String[]{"#", "$"})
        );


        assertEquals(
                "e\n" +
                        "\n" +
                        "bb\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "[\n" +
                        "aaa\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "dc\n" +
                        "\n" +
                        "ce\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "ac\n" +
                        "\n" +
                        "\n" +
                        "ff\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "aa\n" +
                        "\n" +
                        "bd\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "dcb\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "\n" +
                        "aba\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "d\n" +
                        "b\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "eb\n" +
                        "\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "df\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "bfcf\n" +
                        "\n" +
                        "fbd\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "ab\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "ce\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "ee\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "ef\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "ba\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "fd\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "acf\n" +
                        "\n" +
                        "ac\n" +
                        "\n" +
                        "\n" +
                        "db\n" +
                        "]\n" +
                        "\n" +
                        "\n" +
                        "a\n" +
                        "d\n" +
                        "\n" +
                        "f",
                StripComments.stripComments("e\n" +
                        "\n" +
                        "bb\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "[\n" +
                        "aaa\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "dc\n" +
                        "\n" +
                        "ce\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "ac\n" +
                        "\n" +
                        "\n" +
                        "ff\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "aa\n" +
                        "\n" +
                        "bd\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "dcb\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "\n" +
                        "aba\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "d\n" +
                        "b\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "eb\n" +
                        "\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "e\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "df\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "bfcf\n" +
                        "\n" +
                        "fbd\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "ab\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "c\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "ce\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "a\n" +
                        "\n" +
                        "ee\n" +
                        "\n" +
                        "d\n" +
                        "\n" +
                        "ef\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "ba\n" +
                        "\n" +
                        "\n" +
                        "\n" +
                        "b\n" +
                        "\n" +
                        "fd\n" +
                        "\n" +
                        "f\n" +
                        "\n" +
                        "acf\n" +
                        "\n" +
                        "ac\n" +
                        "\n" +
                        "\n" +
                        "db\n" +
                        "]\n" +
                        "\n" +
                        "\n" +
                        "a\n" +
                        "d\n" +
                        "\n" +
                        "f", new String[]{"#", "$"})
        );

    }

}
